Modify the compiled binary to replace the embedded version placeholder
Signed-off-by: Lukas Pukenis <lukas.pukenis@nordsec.com>

diff --git a/net/nordvpn/Makefile b/net/nordvpn/Makefile
--- a/net/nordvpn/Makefile
+++ b/net/nordvpn/Makefile
@@ -34,9 +34,22 @@ define Package/nordvpn/description
 	NordVPN is the gateway to a secure and private access to the internet.
 endef
 
+BINFILE := $(PKG_BUILD_DIR)/target/$(RUSTC_TARGET_ARCH)/release/teliod
+
 define Build/Compile
 	$(info RUSTC_TARGET_ARCH=$(RUSTC_TARGET_ARCH))	
+	$(info PKG_BUILD_DIR=$(PKG_BUILD_DIR))	
+	$(info CARGO_PKG_VARS=$(CARGO_PKG_VARS))
+	
 	cd $(PKG_BUILD_DIR) && $(CARGO_PKG_VARS) BYPASS_LLT_SECRETS=1 cargo build -p teliod --release --target $(RUSTC_TARGET_ARCH)
+
+	find $(PKG_BUILD_DIR)
+	
+	if [ ! -f "$(BINFILE)" ]; then \
+		echo "Build failed, file $(BINFILE) not found"; \
+		exit 1; \
+	fi; \
+	$(CURDIR)/../$(PKG_NAME)/version_placeholder_fix.py "$(BINFILE)" "openwrt-$(PKG_VERSION)"
 endef
 
 define Package/nordvpn/install
